modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/CyclopsMC/ColossalChests/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colossalchests"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="colossalchests"
version="${file.jarVersion}"
displayName="ColossalChests"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/colossal-chests.json"
description='''
For when regular chests are too small.
'''
[[dependencies.colossalchests]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colossalchests]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.50,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colossalchests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,]"
    ordering="NONE"
    side="BOTH"
