modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/ColossalChests/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colossalchests"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="colossalchests"
version="${file.jarVersion}"
displayName="ColossalChests"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/colossal-chests.json"
description='''
For when regular chests are too small.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.colossalchests]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colossalchests]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colossalchests]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
